Fix GPU memory transfer + EwaldInit race condition
N-BodyShop/changa pull request #159
Opened 2024-01-05 00:04 UTC by spencerw

This fixes a race condition where serializeLocal can sometimes be invoked before EwaldInit finishes. An EwaldMsg object is now passed to EwaldGPU, which tells whether EwaldInit, or the callback from the GPU memory transfer invoked it.

Note that the EwaldMsg only contains a single field here. EwaldMsg is used more extensively after the WorkRequest code has been removed from ChaNGa. These changes are contained in a separate pull request.

2024-01-07 00:57 UTC, trquinn requested changes
See code comments.  I'm still testing this out.

2024-01-07 00:57 UTC, trquinn commented on DataManager.cpp
> +          EwaldMsg *msg = new EwaldMsg;
new needs an argument to specify the priority field (in bits).  E.g. "msg = new (8*sizeof(int)) EwaldMsg;"

2024-01-07 00:57 UTC, trquinn commented on Ewald.cpp
> +	EwaldMsg *msg = new EwaldMsg;
See comment on similar line in DataManager.cpp

2024-01-07 00:57 UTC, trquinn commented on ParallelGravity.h
> +struct EwaldMsg: public CkMcastBaseMsg, public CMessage_EwaldMsg {
EwaldMsg does not need to be derived from CkMcastBaseMsg.

2024-01-18 17:53 UTC, spencerw commented
I can confirm that the 'testcosmo' case passes after these changes have been made to the code.

2024-01-18 23:16 UTC, trquinn approved these changes

2024-01-18 23:17 UTC, merged