Unify host pinned memory allocation with hapiHostMalloc
N-BodyShop/changa pull request #79
Opened 2020-08-13 21:32 UTC by minitu

This PR unifies memory allocations for host pinned memory with `hapiHostMalloc`, removing `CUDA_MALLOC`.

`hapiHostMalloc`'s behavior will depend on the compile-time flags: with the default flags in `cuda.mk.in` (`-DHAPI_MEMPOOL` and `-DHAPI_USE_CUDAMALLOCHOST`) the allocations requests will go to the pinned host memory pool managed by HAPI.

2020-08-13 21:44 UTC, minitu commented
Also renamed `HAPI_USE_CUDAMALLOCHOST` to `PINNED_HOST_MEMORY` as this flag is no longer used in HAPI (`hapiHostMalloc` cannot be used to call either `cudaMallocHost` or `malloc` as they have different function signatures), and is now unique to ChaNGa.

2020-09-09 16:10 UTC, trquinn requested changes

2020-09-09 16:10 UTC, trquinn commented on HostCUDA.cu
> +          allocatePinnedHostMemory(bufferHostBuffer, size);
A reference to bufferHostBuffer is needed for the first argument.

2020-09-10 04:40 UTC, trquinn commented
I'm getting `cudaErrorInvalidResourceHandle (error 400) due to "invalid resource handle" on CUDA API call to cudaEventRecord.` when running with more than one thread.  This may be due to some other change.

2020-09-10 16:34 UTC, minitu commented
@trquinn Hmm let me look into that. I suppose this would occur when running with `teststep`?

2020-09-10 18:44 UTC, trquinn commented
Looks like things are broken back at v6.10.2.  I've been using "teststep" with one node and two threads to demonstrate the problem.

2020-09-11 14:07 UTC, trquinn commented
I don't know how the old code ever worked: pool mallocs were not being matched with pool frees.  This PR does at least fix that problem.

2020-09-11 20:47 UTC, minitu commented
@trquinn Can you tell me what your command line was?

I ran teststep on Summit with `jsrun -n1 -a1 -c2 -g1 -K1 -r1 ../ChaNGa -v 1 test_pg.param ++ppn 1 +pemap L0,4` (2 PEs mapped to 1 GPU) with current Charm++ `master` and it seems to run fine, albeit an error at the end of the run:

```
Step: 10.000000 Time: 1.000000 Rungs 0 to 4. Gravity Active: 36000, Gas Active: 0
Domain decomposition ... Sorter: Histograms balanced after 1 iterations.
total 0.00425123 seconds.
Load balancer ... Orb3dLB_notopo: Step 160
took 7.305e-05 seconds.
Building trees ... took 0.0110351 seconds.
Calculating gravity (tree bucket, theta = 0.700000) ... Kick Close:
 Rung 0: 0.05
 Rung 1: 0.025
 Rung 2: 0.0125
 Rung 3: 0.00625
 Rung 4: 0.003125
Calculating gravity and SPH took 0.266413 seconds.
Kick took 0.000291683 seconds.
Finish NodeCache took 2.5914e-05 seconds.
Big step 10 took 3.621373 seconds.
ReOrder particles ... took 0.012273 seconds.
Writing binary file ... took 0.028303 seconds.
Writing arrays ... took 0.000012 seconds.
Domain decomposition ... Sorter: Histograms balanced after 1 iterations.
total 0.00486195 seconds.
Building trees ... took 0.0110406 seconds.
Calculating total densities ... took 0.326643 seconds.
Reodering ... took 0.012242 seconds.
Outputting densities ... took 0.030127 seconds.
[0] Checkpoint starting in pgtest_ms.chk0
Checkpoint to disk finished in 0.053705s, sending out the cb...
Done.

******************

ChaNGa: cudahook.cc:762: CUresult host_free_callback(void*): Assertion `cacheNode != __null' failed.
ERROR:  One or more process (first noticed rank 0) terminated with signal 6 (core dumped)
make: *** [pgtest_ms.log] Error 134
```

The resulting energy seems ok:
```
(base) jchoi@batch3:teststep$ make testenergy
energy should be: -3.2192113384386246e+01
energy is: -32.1915
TEST PASSED
```

2020-09-11 21:27 UTC, trquinn commented
I needed ++ppn of at least 2 to get the error: `../ChaNGa.smp.cuda ++ppn 4 test_pg.param`.

2020-09-11 21:39 UTC, minitu commented
@trquinn Interesting, I can't seem to reproduce the error with `+ppn 2 +pemap L0,4` or `+ppn 4 +pemap L0,4,8,12` on Summit.

2020-09-11 21:43 UTC, minitu commented
I do get the same error when I try to map 4 PEs to 2 GPUs: `jsrun -n1 -a1 -c4 -g2 -K1 -r1 ../ChaNGa -v 1 test_pg.param ++ppn 4 +pemap L0,4,8,12`. I think it has something to do with the PE-GPU mapping.

2020-09-11 21:46 UTC, trquinn commented
Could be: I'm running on a 4 GPU node but only using 1 GPU.

2020-09-11 21:52 UTC, minitu commented
@trquinn Are you limiting the number of GPUs somehow? Because HAPI uses `cudaGetDeviceCount` to determine the number of GPUs, which could return 4 even if you launch just one process.

2020-09-11 22:37 UTC, trquinn commented
I get this to run if I either limit the number of GPUs to 1 or use `+gpumap none`.
Should one of us file a charm issue about this?

2020-09-11 22:52 UTC, minitu commented
@trquinn I see, just created an issue on Charm++ github.

2020-09-11 22:57 UTC, trquinn approved these changes

2020-09-12 04:17 UTC, merged