Remove check when building with Charm++ CUDA build
N-BodyShop/changa pull request #85
Opened 2020-11-27 04:06 UTC by minitu

Since Charm++ CUDA build can be used with both CUDA and non-CUDA builds of ChaNGa, the check that prevents non-CUDA ChaNGa from being built against Charm++ CUDA build should be disabled.

2020-11-27 05:28 UTC, trquinn requested changes
This change also needs to be made in cuda.ac.

2021-01-06 14:11 UTC, hainest commented
The reason this was added is because charmc didn't correctly link the CUDA libraries when ChaNGa wasn't including them in its build. Is this no longer the case?

2021-01-06 15:26 UTC, minitu commented
> The reason this was added is because charmc didn't correctly link the CUDA libraries when ChaNGa wasn't including them in its build. Is this no longer the case?

Yeah that problem has been fixed, currently non-CUDA programs also work (including ChaNGa) with the CUDA build of Charm++.

2021-01-06 15:46 UTC, trquinn approved these changes

2021-01-08 23:38 UTC, merged